export const GET_MATCHES_LIST = 'GET_MATCHES_LIST'
export const GET_MATCHES_LIST_SUCCESS = 'GET_MATCHES_LIST_SUCCESS'
export const GET_MATCHES_LIST_FAILURE = 'GET_MATCHES_LIST_FAILURE'

export const ADD_NEW_MATCH = 'ADD_NEW_MATCH'
export const ADD_NEW_MATCH_SUCCESS = 'ADD_NEW_MATCH_SUCCESS'
export const ADD_NEW_MATCH_FAILURE = 'ADD_NEW_MATCH_FAILURE'

export const ADD_NEW_MATCH_MODAL = 'ADD_NEW_MATCH_MODAL'
